import type { Metadata } from "next";
import { Hachi_Maru_Pop, Bitcount_Grid_Double } from "next/font/google";
import "./globals.css";

// 👇 Load the font using next/font/google
const BitcountGridDouble = Bitcount_Grid_Double ({
  weight: "400", // only 400 is available
  subsets: ["latin"],
  variable: "--font-hachi",
  display: "swap",
});

const hachiMaruPop = Hachi_Maru_Pop ({
  weight: "400", // only 400 is available
  subsets: ["latin"],
  variable: "--font-bitcount",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${hachiMaruPop.variable} ${BitcountGridDouble.variable}`}>
        {children}
      </body>
    </html>
  );
}
